client_config_backend: file
client_config:
    client_id: paste client id here
    client_secret: paste client id here

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive